### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-wikijs#10]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
WikiJS requires a database connection as it is [not shipped with one](https://docs.requarks.io/install/docker#environment-variables).

## Current Behavior
No environment variables are set for the database connection.

## Alternatives Considered
To ask the user to enter the db credentials and more like what you do with [bookstack](https://hub.docker.com/r/linuxserver/bookstack)

**Comment by kenske** [comment]
Seems like this image defaults to using sqlite, but it would be nice to have the option to use other DBs (mysql, postgres)

**Comment by rursache** [comment]
would like to see postgres support as well

**Comment by mzramna** [comment]
according to [this file](https://github.com/linuxserver/docker-wikijs/blob/f8ae1c82b4181487a5aa22f9d1caa51fa794514a/root/etc/s6-overlay/s6-rc.d/init-wikijs-config/run) you just have to set the variables : 
`DB_TYPE=${DB_TYPE:-sqlite}
DB_HOST=${DB_HOST:-mariadb}
DB_PORT=${DB_PORT:-3306}
DB_USER=${DB_USER:-root}
DB_PASS=${DB_PASS:-root}
DB_NAME=${DB_NAME:-wikijs}
DB_FILEPATH=${DB_FILEPATH:-/config/db.sqlite}` to set the database type
