### ISSUE TITLE
Something prevents arm32v7-version-2.5.170 from starting on a raspberry pi with debian buster

### ISSUE THREAD

**Issue by indero** [linuxserver/docker-wikijs#11]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Docker container should start, and be available.

## Current Behavior
Docker container starts but only puts out error messages.

## Steps to Reproduce

On a Raspberry Pi 4
1. `docker pull linuxserver/wikijs:arm32v7-version-2.5.170`
2. `docker run linuxserver/wikijs:arm32v7-version-2.5.170`

Pulling the latest on MacOS does work as expected. And running an older version also works:
`docker run linuxserver/wikijs:arm32v7-2.5.170-ls17`

## Environment
**OS:** Debian Buster
**CPU architecture:** arm32
**How docker service was installed:** Via apt, 5:20.10.2~3-0~debian-buster

## Command used to create docker container (run/create/compose/screenshot)
`docker pull linuxserver/wikijs:arm32v7-version-2.5.170`

## Docker logs
```

         | |  ___   _    __

         | | / __| | |  /  \ 

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/



Brought to you by linuxserver.io

-------------------------------------


To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------


User uid:    911

User gid:    911

-------------------------------------


[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 50-config: executing... 

[cont-init.d] 50-config: exited 0.

[cont-init.d] 99-custom-files: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-files: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.



#

# Fatal error in , line 0

# unreachable code

#

#

#

#FailureMessage Object: 0xbed6123c



#

# Fatal error in , line 0

# unreachable code

#

#

#

#FailureMessage Object: 0xbee5423c



#

# Fatal error in , line 0

# unreachable code

#

#

#

#FailureMessage Object: 0xbee1323c



#

# Fatal error in , line 0

# unreachable code

#

#

#

#FailureMessage Object: 0xbe8b923c



#

# Fatal error in , line 0

# unreachable code

#

#

#

#FailureMessage Object: 0xbefbb23c



#

# Fatal error in , line 0

# unreachable code

#

#

#

#FailureMessage Object: 0xbef9d23c



#

# Fatal error in , line 0

# unreachable code

#

#

#

#FailureMessage Object: 0xbee6023c



#

# Fatal error in , line 0

# unreachable code

#

#

#

#FailureMessage Object: 0xbed8923c
```

**Comment by j0nnymoe** [comment]
The log should show you another above the LSIO artwork. This will have the link you need to get the fix.

**Comment by indero** [comment]
@j0nnymoe Yes, perfect. Installing libseccomp from backports did the trick.
