### ISSUE TITLE
Completelly misconfigured

### ISSUE THREAD

**Issue by icemagno** [linuxserver/docker-wikijs#19]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

The administration interface should be in English

## Current Behavior

The administration interface have no language (all labels are "locale.something"), the "English" option is "0% installed" and I have no option to load another language "Comming Soon" in "locale.title" page

## Steps to Reproduce

1. Docker run
2. Provide initial data for admin
3. Go to admin page

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

docker run -d \
--name=wikijs \
-p 3000:3000 \
-v /srv/wikijs/config:/config \
-v /srv/wikijs/data:/data \
lscr.io/linuxserver/wikijs:latest

**Comment by thespad** [comment]
All seems fine to me with a brand new install - installing new locales works too

![image](https://user-images.githubusercontent.com/8425502/196245240-a0bc463b-8871-4558-9c52-7574eecc1a21.png)
