### ISSUE TITLE
[BUG] <title>How to add hyperlink to footer text

### ISSUE THREAD

**Issue by xiangfeigao** [linuxserver/docker-wikijs#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the footer text is added, it is all text display, and does not support hyperlinks and html language

### Expected Behavior

How to add hyperlink to footer text

### Steps To Reproduce

no

### Environment

```markdown
- OS:debian 
- How docker service was installed:docker 2
```

### CPU architecture

x86-64

### Docker creation

```bash
offical
```

### Container logs

```bash
no
```

**Comment by drizuid** [comment]
We support the container, not the application. Please review the official documentation and seek clarification from the developers of the application.
