### ISSUE TITLE
[BUG] Login from chrome not working in local net

### ISSUE THREAD

**Issue by masterwishx** [linuxserver/docker-wikijs#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

using latest docker in Unraid ,in local address in chrome , but in Firefox all fine

Login successful but not entered to account : 
![image](https://github.com/linuxserver/docker-wikijs/assets/28630321/1e80e5d7-314b-4c64-a45e-6b05cf65f2c0)

### Steps To Reproduce

..

### Environment

```markdown
Docker in Unraid
```

### CPU architecture

x86-64

### Docker creation

```bash
Unraid
```

### Container logs

```bash
Nothing
```

**Comment by homerr** [comment]
This is behaving with no issues for me on Safari/Chrome, and without reverse proxy like you're doing. I'd recommend recreating the container with the commands in the readme to see if that works.

Join us in Discord for further support there are other unraid users around who will be able to assist quicker.

**Comment by masterwishx** [comment]
> This is behaving with no issues for me on Safari/Chrome, and without reverse proxy like you're doing. I'd recommend recreating the container with the commands in the readme to see if that works.

it seems working now after some updates ...
