### ISSUE TITLE
SQLITE_ERROR: too many SQL variables

### ISSUE THREAD

**Issue by kroschu** [linuxserver/docker-wikijs#7]
Error SQLITE_ERROR: too many SQL variables. A table in mardown with 886 lines and a hundred articles, everything, can’t add anything else. I found "SQLite allocates space to hold all host parameters between 1 and the largest host parameter number used. Hence, an SQL statement that contains a host parameter like? 1,000,000,000 would require gigabytes of storage. This could easily overwhelm the resources of the host machine . To prevent excessive memory allocations, the maximum value of a host parameter number is SQLITE_MAX_VARIABLE_NUMBER, which defaults to 999. " . Maybe add SQLITE_MAX_VARIABLE_NUMBER as a parameter in the Dockerfile. I need to increase its value.

**Comment by j0nnymoe** [comment]
Please fill in the issue template with the requested information.

**Comment by j0nnymoe** [comment]
Closed due to no response.
